scripts:
    - js/jquery.min.js
    - js/uikit.min.js
    - https://getuikit.com/migrate.min.js

styles:
    - css/uikit.min.css
    - css/index.css

menu:
  - home
  - about
  - works
  - services
  - contact

work_type:
  - all
  - personal
  - professional
  - universitary
  
work_modal: modal_work_

language: fr